<?xml version="1.0" encoding="UTF-8"?>
<com.ibm.datatools.etl.errmsgs:Message xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:com.ibm.datatools.etl.errmsgs="http:///com/ibm/datatools/etl/errmsgs.ecore" msgNum="12208" timestamp="1548320859678" msgTxt="Validation succeeded for the 'Q2'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for Q2." msgCause="" msgResponse="" entityType="DataFlow">
  <expandedMsgs msgNum="12208" timestamp="1548320859678" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="02"/>
  <expandedMsgs msgNum="12208" timestamp="1548320859678" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="03"/>
  <expandedMsgs msgNum="12208" timestamp="1548320859678" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="05"/>
</com.ibm.datatools.etl.errmsgs:Message>
